### ISSUE TITLE
Add NSLA overlay to rules layer

### ISSUE THREAD

**Issue by lissertations** [hughrun/public_library_map#119]
I recognise that most NSLA libraries do not fulfil the functions of a public library (that is all of them except Libraries ACT and Libraries Tasmania) and therefore do not have loans or fines periods as they are largely non-lending. However, they do have library management systems that do not appear on the relevant layers. I found myself wanting to know this morning which ILS a particular state library used, thought 'oh! Library Map can tell me!' and went to have a look but as it happens Library Map could not tell me :( Is there scope to include this data, or is it restricted to bona fide public libraries?

**Comment by hughrun** [comment]
How annoying!

Hmm, this could be done a couple of different ways. The issue currently is the state libraries are mapped as location points rather than as shapes (i.e. they are treated as library buildings rather than library services). So we can either make another layer showing state library _jurisdictions_ to enable mapping of ILS the same way we do for public library services(i.e. a map of each state and territory) or we could add ILS information to the library locations file and then display that when the user click on a library building. I guess there's probably other options too. Thoughts on these options @lissertations ?

**Comment by lissertations** [comment]
hm, it would make more sense to create another layer rather than adding that info to the locations file (bc it really is service-specific info rather than building- or location-specific) but on the other hand a whole extra layer for NSLA libraries might be overkill... would it be possible to carve out a small section of space in the existing rules layer for each NSLA library building, but treat it as a 'service' and include the relevant data?

**Comment by hughrun** [comment]
hmm we could probably make it an overlay in the rules layer, much like NSLA is an overlay in the library buildings layer. i.e. the default layer is public library services but there's an alternate layer for state libraries

**Comment by lissertations** [comment]
This sounds like a good solution 👍🏻

**Comment by hughrun** [comment]
Ok I am working on this but it turns out I ...don't actually have that information! Any tips on which ILS is used by which NSLA library gratefully received.
