### ISSUE TITLE
Mobile library services

### ISSUE THREAD

**Issue by lissertations** [hughrun/public_library_map#69]
Around 14 mobile libraries, all bar one of which are in Queensland, are included in `public_library_locations.csv`. Mobile library stopping points might be a useful feature where the data exists, but are probably not appropriate for a static locations view. What should be done with this data?

![image](https://user-images.githubusercontent.com/22556371/106231397-bf7f7980-6245-11eb-8509-7074c6fb3378.png)

**Comment by hughrun** [comment]
yikes, that map isn't useful is it? hehe

Good question, perhaps someone else will have an answer. I'd very much like to add mobile library stops, but the data is a bit harder to get than static locations, definitely needs to be a different colour at least, and probably needs to be mapped differently as you've noted @lissertations

**Comment by sallybaker** [comment]
Agreed that a different colour might be useful. 

What about if the circle radius for mobile libraries were extended from the 800m for other libraries, so that the circle encompassed a larger region on the map? Not sure what distance would be appropriate though given the size of towns varies quite a bit. 

Perhaps a filter checkbox added to the filter list as well?

**Comment by hughrun** [comment]
For now I have removed this data from the branch locations file - it's very hit and miss so it's simply confusing at this point.
